version = 0.1
[default.deploy.parameters]
stack_name = "Ecommerce-backend"
resolve_s3 = true
s3_prefix = "Ecommerce-backend"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MongoUri=\"mongodb+srv://princekumar007p:PRINCEkumar910@cluster0.un8m3gh.mongodb.net/E-commerce-Backend\" jwtSecretKey=\"1234567890\""
image_repositories = []
confirm_changeset = true
